apiVersion: "cis.f5.com/v1"
kind: IngressLink
metadata:
  name: vs-ingresslink
  namespace: nginx-ingress
spec:
  virtualServerAddress: "10.0.2.100"
  iRules:
    - /Common/Shared/Proxy_Protocol_iRule
  selector:
    matchLabels:
      app: nginx-ingress
